name: ZJU-nCov-Hitcarder Sample

on:
  workflow_dispatch:
  schedule:
    - cron: "30 2 * * *"

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - username: ZJU_USERNAME
            password: ZJU_PASSWORD
            dingtalk_token: DINGTALK_TOKEN
            pushplus_token: PUSHPLUS_TOKEN
            serverchan_key: SERVERCHAN_KEY
   steps:
          - name: Working
   uses:  muda2670630704 /zju-ncov-hitcarder@0.0.x
      with:
         # zju account username(student  id).
         username: ${{ secrets.ZJU_USERNAME }}
         # zju account password.
         password: ${{ secrets.ZJU_PASSWORD }}
         # (optional) dingtalk_token.
         dingtalk_token: ${{ secrets.DINGTALK_TOKEN }}
         # (optional) serverchan_key.
         serverchan_key: ${{ secrets.SERVERCHAN_KEY }}
